export interface Quest {
  id: string;
  type: "daily" | "weekly" | "monthly";
  title: string;
  icon: string;
  levelReq: number;
  description: string;
  goal: string;
  rewardSC: number;
  rewardXP: number;
  minPartySize?: number; // 2, 4, or 8
  bgColorClass: string;
  textColorClass: string;
  borderColorClass: string;
}

export const questsData: Quest[] = [
  // ==========================================
  // DAILY QUESTS (10 Quests: 5 Solo, 5 Group)
  // ==========================================
  {
    id: "d-1",
    type: "daily",
    title: "🌲 Green Forestry",
    icon: "TreePine",
    levelReq: 1,
    description: "Plant at least 3 trees in the grid using the arborist permit.",
    goal: "3 trees planted",
    rewardSC: 100,
    rewardXP: 30,
    bgColorClass: "bg-emerald-500/10",
    textColorClass: "text-emerald-400",
    borderColorClass: "border-emerald-500/20",
  },
  {
    id: "d-2",
    type: "daily",
    title: "🏃 Morning Jog",
    icon: "Activity",
    levelReq: 1,
    description: "Sprint for a total distance of 500 meters during the morning simulation hours without exhausting your stamina.",
    goal: "Sprint 500m",
    rewardSC: 50,
    rewardXP: 20,
    bgColorClass: "bg-cyan-500/10",
    textColorClass: "text-cyan-400",
    borderColorClass: "border-cyan-500/20",
  },
  {
    id: "d-3",
    type: "daily",
    title: "🍔 Fast Food Run",
    icon: "Pizza",
    levelReq: 2,
    description: "Stave off hunger by purchasing and eating a meal at any local fast food restaurant.",
    goal: "Eat 1 Fast Food Meal",
    rewardSC: 150,
    rewardXP: 45,
    bgColorClass: "bg-amber-500/10",
    textColorClass: "text-amber-400",
    borderColorClass: "border-amber-500/20",
  },
  {
    id: "d-4",
    type: "daily",
    title: "🗣️ Social Butterfly",
    icon: "MessageCircle",
    levelReq: 1,
    description: "Talk to at least 3 wandering NPCs to learn more about the city.",
    goal: "Talk to 3 NPCs",
    rewardSC: 80,
    rewardXP: 25,
    bgColorClass: "bg-violet-500/10",
    textColorClass: "text-violet-400",
    borderColorClass: "border-violet-500/20",
  },
  {
    id: "d-5",
    type: "daily",
    title: "🌃 Night Owl",
    icon: "Moon",
    levelReq: 3,
    description: "Stay active in the city past midnight and visit an open commercial outlet.",
    goal: "Visit shop after midnight",
    rewardSC: 120,
    rewardXP: 40,
    bgColorClass: "bg-indigo-500/10",
    textColorClass: "text-indigo-400",
    borderColorClass: "border-indigo-500/20",
  },
  // GROUP DAILY QUESTS (5)
  {
    id: "d-6",
    type: "daily",
    title: "🤝 Buddy Walk",
    icon: "Users",
    levelReq: 1,
    minPartySize: 2,
    description: "Form a party of 2 and walk together from one side of the city to the other.",
    goal: "Walk 1km with a party member",
    rewardSC: 200,
    rewardXP: 60,
    bgColorClass: "bg-fuchsia-500/10",
    textColorClass: "text-fuchsia-400",
    borderColorClass: "border-fuchsia-500/20",
  },
  {
    id: "d-7",
    type: "daily",
    title: "🍽️ Group Dinner",
    icon: "Utensils",
    levelReq: 2,
    minPartySize: 4,
    description: "Gather a party of 4 and eat at a restaurant together at the exact same time.",
    goal: "Eat with 3 other party members",
    rewardSC: 400,
    rewardXP: 100,
    bgColorClass: "bg-orange-500/10",
    textColorClass: "text-orange-400",
    borderColorClass: "border-orange-500/20",
  },
  {
    id: "d-8",
    type: "daily",
    title: "🚧 Co-op Blueprint",
    icon: "Hammer",
    levelReq: 3,
    minPartySize: 2,
    description: "Both party members must contribute to the same construction site.",
    goal: "Contribute to a party member's building",
    rewardSC: 350,
    rewardXP: 80,
    bgColorClass: "bg-blue-500/10",
    textColorClass: "text-blue-400",
    borderColorClass: "border-blue-500/20",
  },
  {
    id: "d-9",
    type: "daily",
    title: "✂️ Style Squad",
    icon: "Scissors",
    levelReq: 2,
    minPartySize: 2,
    description: "Visit the barbershop and get matching outfits/hairstyles with your party member.",
    goal: "Get haircuts together",
    rewardSC: 250,
    rewardXP: 50,
    bgColorClass: "bg-rose-500/10",
    textColorClass: "text-rose-400",
    borderColorClass: "border-rose-500/20",
  },
  {
    id: "d-10",
    type: "daily",
    title: "📸 Squad Selfie",
    icon: "Camera",
    levelReq: 1,
    minPartySize: 4,
    description: "Gather 4 party members on the roof of a skyscraper.",
    goal: "4 members on a roof",
    rewardSC: 500,
    rewardXP: 120,
    bgColorClass: "bg-yellow-500/10",
    textColorClass: "text-yellow-400",
    borderColorClass: "border-yellow-500/20",
  },

  // ==========================================
  // WEEKLY QUESTS (20 Quests: 10 Solo, 10 Group)
  // ==========================================
  {
    id: "w-1",
    type: "weekly",
    title: "🏗️ Master Builder",
    icon: "Building",
    levelReq: 4,
    description: "Construct 3 fully completed commercial properties (Restaurants or Cloth Shops).",
    goal: "Build 3 commercial shops",
    rewardSC: 1500,
    rewardXP: 400,
    bgColorClass: "bg-slate-500/10",
    textColorClass: "text-slate-400",
    borderColorClass: "border-slate-500/20",
  },
  {
    id: "w-2",
    type: "weekly",
    title: "💰 Tax Collector",
    icon: "Coins",
    levelReq: 5,
    description: "Earn a total of 5,000 SC in passive revenue from your owned shops over the week.",
    goal: "Collect 5,000 SC tax",
    rewardSC: 2000,
    rewardXP: 500,
    bgColorClass: "bg-amber-500/10",
    textColorClass: "text-amber-400",
    borderColorClass: "border-amber-500/20",
  },
  {
    id: "w-3",
    type: "weekly",
    title: "🌳 Urban Oasis",
    icon: "TreePine",
    levelReq: 3,
    description: "Plant a total of 50 trees in barren grid sectors to improve city aesthetics.",
    goal: "Plant 50 trees",
    rewardSC: 800,
    rewardXP: 250,
    bgColorClass: "bg-emerald-500/10",
    textColorClass: "text-emerald-400",
    borderColorClass: "border-emerald-500/20",
  },
  {
    id: "w-4",
    type: "weekly",
    title: "🍩 Donut Devourer",
    icon: "Pizza",
    levelReq: 2,
    description: "Eat 15 donuts from commercial outlets over the course of the week.",
    goal: "Eat 15 donuts",
    rewardSC: 500,
    rewardXP: 150,
    bgColorClass: "bg-pink-500/10",
    textColorClass: "text-pink-400",
    borderColorClass: "border-pink-500/20",
  },
  {
    id: "w-5",
    type: "weekly",
    title: "🏃 Marathon Runner",
    icon: "Activity",
    levelReq: 3,
    description: "Sprint a cumulative distance of 20 kilometers within the city.",
    goal: "Sprint 20km",
    rewardSC: 1000,
    rewardXP: 300,
    bgColorClass: "bg-cyan-500/10",
    textColorClass: "text-cyan-400",
    borderColorClass: "border-cyan-500/20",
  },
  {
    id: "w-6",
    type: "weekly",
    title: "🚔 Citizen Patrol",
    icon: "ShieldAlert",
    levelReq: 6,
    description: "Visit the Central Police Station 7 times, once per day, to report on city activities.",
    goal: "Visit police station 7 days",
    rewardSC: 1200,
    rewardXP: 350,
    bgColorClass: "bg-blue-500/10",
    textColorClass: "text-blue-400",
    borderColorClass: "border-blue-500/20",
  },
  {
    id: "w-7",
    type: "weekly",
    title: "👕 Fashion Icon",
    icon: "Scissors",
    levelReq: 4,
    description: "Purchase 5 unique clothing outfits from the boutique.",
    goal: "Buy 5 outfits",
    rewardSC: 800,
    rewardXP: 200,
    bgColorClass: "bg-fuchsia-500/10",
    textColorClass: "text-fuchsia-400",
    borderColorClass: "border-fuchsia-500/20",
  },
  {
    id: "w-8",
    type: "weekly",
    title: "🏠 Landlord",
    icon: "Home",
    levelReq: 5,
    description: "Successfully pay your housing rent for 7 consecutive in-game nights without going bankrupt.",
    goal: "Pay 7 nights of rent",
    rewardSC: 1500,
    rewardXP: 400,
    bgColorClass: "bg-indigo-500/10",
    textColorClass: "text-indigo-400",
    borderColorClass: "border-indigo-500/20",
  },
  {
    id: "w-9",
    type: "weekly",
    title: "⚡ Energy Conservation",
    icon: "Zap",
    levelReq: 2,
    description: "Survive 3 full day-night cycles without ever dropping below 20% stamina.",
    goal: "Maintain stamina > 20% for 3 days",
    rewardSC: 600,
    rewardXP: 200,
    bgColorClass: "bg-yellow-500/10",
    textColorClass: "text-yellow-400",
    borderColorClass: "border-yellow-500/20",
  },
  {
    id: "w-10",
    type: "weekly",
    title: "🗺️ Explorer",
    icon: "Compass",
    levelReq: 1,
    description: "Visit all 4 corner boundaries of the simulated city grid.",
    goal: "Visit 4 corners",
    rewardSC: 1000,
    rewardXP: 250,
    bgColorClass: "bg-teal-500/10",
    textColorClass: "text-teal-400",
    borderColorClass: "border-teal-500/20",
  },

  // GROUP WEEKLY QUESTS (10)
  {
    id: "w-11",
    type: "weekly",
    title: "🏘️ Suburb Planners",
    icon: "Building",
    levelReq: 5,
    minPartySize: 4,
    description: "As a party of 4, construct 4 adjacent houses in a square block.",
    goal: "Build 4 adjacent houses (Party of 4)",
    rewardSC: 4000,
    rewardXP: 1000,
    bgColorClass: "bg-blue-500/10",
    textColorClass: "text-blue-400",
    borderColorClass: "border-blue-500/20",
  },
  {
    id: "w-12",
    type: "weekly",
    title: "🏃‍♂️ Relay Race",
    icon: "Activity",
    levelReq: 3,
    minPartySize: 4,
    description: "Sprint in a relay format where 4 members touch each corner of the map simultaneously.",
    goal: "4 members at 4 corners (Party of 4)",
    rewardSC: 3500,
    rewardXP: 800,
    bgColorClass: "bg-red-500/10",
    textColorClass: "text-red-400",
    borderColorClass: "border-red-500/20",
  },
  {
    id: "w-13",
    type: "weekly",
    title: "🛒 Shopping Spree",
    icon: "Store",
    levelReq: 4,
    minPartySize: 2,
    description: "Party members must spend a combined total of 10,000 SC at commercial outlets.",
    goal: "Spend 10k SC together",
    rewardSC: 3000,
    rewardXP: 700,
    bgColorClass: "bg-amber-500/10",
    textColorClass: "text-amber-400",
    borderColorClass: "border-amber-500/20",
  },
  {
    id: "w-14",
    type: "weekly",
    title: "👥 Networking Event",
    icon: "Users",
    levelReq: 2,
    minPartySize: 8,
    description: "Form a maximum-size party of 8 members and stand together in the central plaza for 5 minutes.",
    goal: "8 players in plaza (Party of 8)",
    rewardSC: 8000,
    rewardXP: 2000,
    bgColorClass: "bg-fuchsia-500/10",
    textColorClass: "text-fuchsia-400",
    borderColorClass: "border-fuchsia-500/20",
  },
  {
    id: "w-15",
    type: "weekly",
    title: "🌳 Central Park Co-op",
    icon: "TreePine",
    levelReq: 3,
    minPartySize: 4,
    description: "As a group of 4, plant 100 trees in a designated park sector.",
    goal: "Plant 100 trees (Party of 4)",
    rewardSC: 2500,
    rewardXP: 600,
    bgColorClass: "bg-emerald-500/10",
    textColorClass: "text-emerald-400",
    borderColorClass: "border-emerald-500/20",
  },
  {
    id: "w-16",
    type: "weekly",
    title: "🍽️ Banquet Feast",
    icon: "Pizza",
    levelReq: 4,
    minPartySize: 8,
    description: "An 8-player party must eat at the same restaurant inside a 10-minute window.",
    goal: "8 players eat together",
    rewardSC: 5000,
    rewardXP: 1200,
    bgColorClass: "bg-orange-500/10",
    textColorClass: "text-orange-400",
    borderColorClass: "border-orange-500/20",
  },
  {
    id: "w-17",
    type: "weekly",
    title: "🚨 Neighborhood Watch",
    icon: "ShieldAlert",
    levelReq: 5,
    minPartySize: 4,
    description: "Patrol the city. 4 party members must each visit a different corner of the city during night hours.",
    goal: "4 members patrol night corners",
    rewardSC: 3000,
    rewardXP: 750,
    bgColorClass: "bg-indigo-500/10",
    textColorClass: "text-indigo-400",
    borderColorClass: "border-indigo-500/20",
  },
  {
    id: "w-18",
    type: "weekly",
    title: "🏢 Skyscraper Syndicate",
    icon: "Building",
    levelReq: 6,
    minPartySize: 2,
    description: "A party of 2 must each build a skyscraper next to each other.",
    goal: "Build 2 adjacent skyscrapers",
    rewardSC: 6000,
    rewardXP: 1500,
    bgColorClass: "bg-slate-500/10",
    textColorClass: "text-slate-400",
    borderColorClass: "border-slate-500/20",
  },
  {
    id: "w-19",
    type: "weekly",
    title: "💬 Flash Mob",
    icon: "MessageCircle",
    levelReq: 2,
    minPartySize: 8,
    description: "All 8 members must interact with the exact same NPC simultaneously.",
    goal: "8 members talk to 1 NPC",
    rewardSC: 4000,
    rewardXP: 1000,
    bgColorClass: "bg-pink-500/10",
    textColorClass: "text-pink-400",
    borderColorClass: "border-pink-500/20",
  },
  {
    id: "w-20",
    type: "weekly",
    title: "⚡ Synchronized Sprint",
    icon: "Zap",
    levelReq: 3,
    minPartySize: 4,
    description: "4 party members must drain their stamina to 0% at the exact same moment.",
    goal: "Sync stamina drain (Party of 4)",
    rewardSC: 2000,
    rewardXP: 500,
    bgColorClass: "bg-yellow-500/10",
    textColorClass: "text-yellow-400",
    borderColorClass: "border-yellow-500/20",
  },

  // ==========================================
  // MONTHLY QUESTS (40 Quests: 20 Solo, 20 Group)
  // ==========================================
  // Solo Monthly
  ...Array.from({ length: 20 }).map((_, i) => ({
    id: `m-solo-${i + 1}`,
    type: "monthly" as const,
    title: `🏆 Monthly Solo Milestone ${i + 1}`,
    icon: "Trophy",
    levelReq: 5 + Math.floor(i / 2),
    description: `A long-term solo achievement requiring dedication. Phase ${i + 1} of the monthly progression involving immense capital and time investment in the city.`,
    goal: `Complete Monthly Solo Task ${i + 1}`,
    rewardSC: 10000 + i * 500,
    rewardXP: 2500 + i * 100,
    bgColorClass: "bg-slate-500/10",
    textColorClass: "text-slate-400",
    borderColorClass: "border-slate-500/20",
  })),

  // Group Monthly
  ...Array.from({ length: 20 }).map((_, i) => ({
    id: `m-group-${i + 1}`,
    type: "monthly" as const,
    title: `🤝 Epic Syndicate Raid ${i + 1}`,
    icon: "Users",
    levelReq: 8 + Math.floor(i / 2),
    minPartySize: i % 3 === 0 ? 8 : (i % 2 === 0 ? 4 : 2),
    description: `An extremely difficult coordination task requiring an organized party. Phase ${i + 1} of the Syndicate raids.`,
    goal: `Complete Syndicate Task ${i + 1}`,
    rewardSC: 20000 + i * 1000,
    rewardXP: 5000 + i * 200,
    bgColorClass: "bg-amber-500/10",
    textColorClass: "text-amber-400",
    borderColorClass: "border-amber-500/20",
  })),
];
